<?php

namespace Magenest\ProductPrediction\Model\ResourceModel\CustomerHistory;

use Magenest\ProductPrediction\Model\CustomerHistory as CustomerHistoryModel;
use Magenest\ProductPrediction\Model\ResourceModel\CustomerHistory as CustomerHistoryResourceModel;

class Collection extends \Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection
{
    protected function _construct()
    {
        $this->_init(CustomerHistoryModel::class, CustomerHistoryResourceModel::class);
    }

    /**
     * @return $this|Collection|void
     */
    protected function _initSelect()
    {
        parent::_initSelect();
        $customer = $this->getTable('customer_entity');
        $this->getSelect()
            ->joinLeft($customer, 'main_table.user_id =' .$customer.'.entity_id',['firstname', 'lastname','email']);
        return $this; // TODO: Change the autogenerated stub
    }
}
